// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomicswap.proto

package protobind

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingWalletRpcRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Hostport             string   `protobuf:"bytes,5,opt,name=hostport,proto3" json:"hostport,omitempty"`
	Rpcuser              string   `protobuf:"bytes,6,opt,name=rpcuser,proto3" json:"rpcuser,omitempty"`
	Rpcpass              string   `protobuf:"bytes,7,opt,name=rpcpass,proto3" json:"rpcpass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingWalletRpcRequest) Reset()         { *m = PingWalletRpcRequest{} }
func (m *PingWalletRpcRequest) String() string { return proto.CompactTextString(m) }
func (*PingWalletRpcRequest) ProtoMessage()    {}
func (*PingWalletRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{0}
}

func (m *PingWalletRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingWalletRpcRequest.Unmarshal(m, b)
}
func (m *PingWalletRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingWalletRpcRequest.Marshal(b, m, deterministic)
}
func (m *PingWalletRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingWalletRpcRequest.Merge(m, src)
}
func (m *PingWalletRpcRequest) XXX_Size() int {
	return xxx_messageInfo_PingWalletRpcRequest.Size(m)
}
func (m *PingWalletRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingWalletRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingWalletRpcRequest proto.InternalMessageInfo

func (m *PingWalletRpcRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *PingWalletRpcRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *PingWalletRpcRequest) GetHostport() string {
	if m != nil {
		return m.Hostport
	}
	return ""
}

func (m *PingWalletRpcRequest) GetRpcuser() string {
	if m != nil {
		return m.Rpcuser
	}
	return ""
}

func (m *PingWalletRpcRequest) GetRpcpass() string {
	if m != nil {
		return m.Rpcpass
	}
	return ""
}

type PingWalletRpcResponse struct {
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingWalletRpcResponse) Reset()         { *m = PingWalletRpcResponse{} }
func (m *PingWalletRpcResponse) String() string { return proto.CompactTextString(m) }
func (*PingWalletRpcResponse) ProtoMessage()    {}
func (*PingWalletRpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{1}
}

func (m *PingWalletRpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingWalletRpcResponse.Unmarshal(m, b)
}
func (m *PingWalletRpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingWalletRpcResponse.Marshal(b, m, deterministic)
}
func (m *PingWalletRpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingWalletRpcResponse.Merge(m, src)
}
func (m *PingWalletRpcResponse) XXX_Size() int {
	return xxx_messageInfo_PingWalletRpcResponse.Size(m)
}
func (m *PingWalletRpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingWalletRpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingWalletRpcResponse proto.InternalMessageInfo

func (m *PingWalletRpcResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *PingWalletRpcResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type NewAddressRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Hostport             string   `protobuf:"bytes,5,opt,name=hostport,proto3" json:"hostport,omitempty"`
	Rpcuser              string   `protobuf:"bytes,6,opt,name=rpcuser,proto3" json:"rpcuser,omitempty"`
	Rpcpass              string   `protobuf:"bytes,7,opt,name=rpcpass,proto3" json:"rpcpass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAddressRequest) Reset()         { *m = NewAddressRequest{} }
func (m *NewAddressRequest) String() string { return proto.CompactTextString(m) }
func (*NewAddressRequest) ProtoMessage()    {}
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{2}
}

func (m *NewAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAddressRequest.Unmarshal(m, b)
}
func (m *NewAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAddressRequest.Marshal(b, m, deterministic)
}
func (m *NewAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAddressRequest.Merge(m, src)
}
func (m *NewAddressRequest) XXX_Size() int {
	return xxx_messageInfo_NewAddressRequest.Size(m)
}
func (m *NewAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAddressRequest proto.InternalMessageInfo

func (m *NewAddressRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *NewAddressRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *NewAddressRequest) GetHostport() string {
	if m != nil {
		return m.Hostport
	}
	return ""
}

func (m *NewAddressRequest) GetRpcuser() string {
	if m != nil {
		return m.Rpcuser
	}
	return ""
}

func (m *NewAddressRequest) GetRpcpass() string {
	if m != nil {
		return m.Rpcpass
	}
	return ""
}

type NewAddressResponse struct {
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAddressResponse) Reset()         { *m = NewAddressResponse{} }
func (m *NewAddressResponse) String() string { return proto.CompactTextString(m) }
func (*NewAddressResponse) ProtoMessage()    {}
func (*NewAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{3}
}

func (m *NewAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAddressResponse.Unmarshal(m, b)
}
func (m *NewAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAddressResponse.Marshal(b, m, deterministic)
}
func (m *NewAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAddressResponse.Merge(m, src)
}
func (m *NewAddressResponse) XXX_Size() int {
	return xxx_messageInfo_NewAddressResponse.Size(m)
}
func (m *NewAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewAddressResponse proto.InternalMessageInfo

func (m *NewAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewAddressResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *NewAddressResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type InitiateRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Hostport             string   `protobuf:"bytes,5,opt,name=hostport,proto3" json:"hostport,omitempty"`
	Rpcuser              string   `protobuf:"bytes,6,opt,name=rpcuser,proto3" json:"rpcuser,omitempty"`
	Rpcpass              string   `protobuf:"bytes,7,opt,name=rpcpass,proto3" json:"rpcpass,omitempty"`
	PartAddress          string   `protobuf:"bytes,8,opt,name=part_address,json=partAddress,proto3" json:"part_address,omitempty"`
	Amount               int64    `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiateRequest) Reset()         { *m = InitiateRequest{} }
func (m *InitiateRequest) String() string { return proto.CompactTextString(m) }
func (*InitiateRequest) ProtoMessage()    {}
func (*InitiateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{4}
}

func (m *InitiateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiateRequest.Unmarshal(m, b)
}
func (m *InitiateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiateRequest.Marshal(b, m, deterministic)
}
func (m *InitiateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiateRequest.Merge(m, src)
}
func (m *InitiateRequest) XXX_Size() int {
	return xxx_messageInfo_InitiateRequest.Size(m)
}
func (m *InitiateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitiateRequest proto.InternalMessageInfo

func (m *InitiateRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *InitiateRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *InitiateRequest) GetHostport() string {
	if m != nil {
		return m.Hostport
	}
	return ""
}

func (m *InitiateRequest) GetRpcuser() string {
	if m != nil {
		return m.Rpcuser
	}
	return ""
}

func (m *InitiateRequest) GetRpcpass() string {
	if m != nil {
		return m.Rpcpass
	}
	return ""
}

func (m *InitiateRequest) GetPartAddress() string {
	if m != nil {
		return m.PartAddress
	}
	return ""
}

func (m *InitiateRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type InitiateResponse struct {
	Secret               string   `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	Secrethash           string   `protobuf:"bytes,6,opt,name=secrethash,proto3" json:"secrethash,omitempty"`
	Contract             string   `protobuf:"bytes,7,opt,name=contract,proto3" json:"contract,omitempty"`
	ContractP2Sh         string   `protobuf:"bytes,8,opt,name=contract_p2sh,json=contractP2sh,proto3" json:"contract_p2sh,omitempty"`
	ContractTx           string   `protobuf:"bytes,9,opt,name=contract_tx,json=contractTx,proto3" json:"contract_tx,omitempty"`
	ContractTxHash       string   `protobuf:"bytes,10,opt,name=contract_tx_hash,json=contractTxHash,proto3" json:"contract_tx_hash,omitempty"`
	Fee                  int64    `protobuf:"varint,11,opt,name=fee,proto3" json:"fee,omitempty"`
	Feerate              float32  `protobuf:"fixed32,12,opt,name=feerate,proto3" json:"feerate,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiateResponse) Reset()         { *m = InitiateResponse{} }
func (m *InitiateResponse) String() string { return proto.CompactTextString(m) }
func (*InitiateResponse) ProtoMessage()    {}
func (*InitiateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{5}
}

func (m *InitiateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiateResponse.Unmarshal(m, b)
}
func (m *InitiateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiateResponse.Marshal(b, m, deterministic)
}
func (m *InitiateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiateResponse.Merge(m, src)
}
func (m *InitiateResponse) XXX_Size() int {
	return xxx_messageInfo_InitiateResponse.Size(m)
}
func (m *InitiateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitiateResponse proto.InternalMessageInfo

func (m *InitiateResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *InitiateResponse) GetSecrethash() string {
	if m != nil {
		return m.Secrethash
	}
	return ""
}

func (m *InitiateResponse) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *InitiateResponse) GetContractP2Sh() string {
	if m != nil {
		return m.ContractP2Sh
	}
	return ""
}

func (m *InitiateResponse) GetContractTx() string {
	if m != nil {
		return m.ContractTx
	}
	return ""
}

func (m *InitiateResponse) GetContractTxHash() string {
	if m != nil {
		return m.ContractTxHash
	}
	return ""
}

func (m *InitiateResponse) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *InitiateResponse) GetFeerate() float32 {
	if m != nil {
		return m.Feerate
	}
	return 0
}

func (m *InitiateResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *InitiateResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type ParticipateRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Hostport             string   `protobuf:"bytes,5,opt,name=hostport,proto3" json:"hostport,omitempty"`
	Rpcuser              string   `protobuf:"bytes,6,opt,name=rpcuser,proto3" json:"rpcuser,omitempty"`
	Rpcpass              string   `protobuf:"bytes,7,opt,name=rpcpass,proto3" json:"rpcpass,omitempty"`
	Secrethash           string   `protobuf:"bytes,8,opt,name=secrethash,proto3" json:"secrethash,omitempty"`
	PartAddress          string   `protobuf:"bytes,9,opt,name=part_address,json=partAddress,proto3" json:"part_address,omitempty"`
	Amount               int64    `protobuf:"varint,10,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipateRequest) Reset()         { *m = ParticipateRequest{} }
func (m *ParticipateRequest) String() string { return proto.CompactTextString(m) }
func (*ParticipateRequest) ProtoMessage()    {}
func (*ParticipateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{6}
}

func (m *ParticipateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipateRequest.Unmarshal(m, b)
}
func (m *ParticipateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipateRequest.Marshal(b, m, deterministic)
}
func (m *ParticipateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipateRequest.Merge(m, src)
}
func (m *ParticipateRequest) XXX_Size() int {
	return xxx_messageInfo_ParticipateRequest.Size(m)
}
func (m *ParticipateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipateRequest proto.InternalMessageInfo

func (m *ParticipateRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *ParticipateRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *ParticipateRequest) GetHostport() string {
	if m != nil {
		return m.Hostport
	}
	return ""
}

func (m *ParticipateRequest) GetRpcuser() string {
	if m != nil {
		return m.Rpcuser
	}
	return ""
}

func (m *ParticipateRequest) GetRpcpass() string {
	if m != nil {
		return m.Rpcpass
	}
	return ""
}

func (m *ParticipateRequest) GetSecrethash() string {
	if m != nil {
		return m.Secrethash
	}
	return ""
}

func (m *ParticipateRequest) GetPartAddress() string {
	if m != nil {
		return m.PartAddress
	}
	return ""
}

func (m *ParticipateRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ParticipateResponse struct {
	Contract             string   `protobuf:"bytes,5,opt,name=contract,proto3" json:"contract,omitempty"`
	ContractP2Sh         string   `protobuf:"bytes,6,opt,name=contract_p2sh,json=contractP2sh,proto3" json:"contract_p2sh,omitempty"`
	ContractTx           string   `protobuf:"bytes,7,opt,name=contract_tx,json=contractTx,proto3" json:"contract_tx,omitempty"`
	ContractTxHash       string   `protobuf:"bytes,8,opt,name=contract_tx_hash,json=contractTxHash,proto3" json:"contract_tx_hash,omitempty"`
	Fee                  int64    `protobuf:"varint,9,opt,name=fee,proto3" json:"fee,omitempty"`
	Feerate              float32  `protobuf:"fixed32,10,opt,name=feerate,proto3" json:"feerate,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipateResponse) Reset()         { *m = ParticipateResponse{} }
func (m *ParticipateResponse) String() string { return proto.CompactTextString(m) }
func (*ParticipateResponse) ProtoMessage()    {}
func (*ParticipateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{7}
}

func (m *ParticipateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipateResponse.Unmarshal(m, b)
}
func (m *ParticipateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipateResponse.Marshal(b, m, deterministic)
}
func (m *ParticipateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipateResponse.Merge(m, src)
}
func (m *ParticipateResponse) XXX_Size() int {
	return xxx_messageInfo_ParticipateResponse.Size(m)
}
func (m *ParticipateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipateResponse proto.InternalMessageInfo

func (m *ParticipateResponse) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ParticipateResponse) GetContractP2Sh() string {
	if m != nil {
		return m.ContractP2Sh
	}
	return ""
}

func (m *ParticipateResponse) GetContractTx() string {
	if m != nil {
		return m.ContractTx
	}
	return ""
}

func (m *ParticipateResponse) GetContractTxHash() string {
	if m != nil {
		return m.ContractTxHash
	}
	return ""
}

func (m *ParticipateResponse) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *ParticipateResponse) GetFeerate() float32 {
	if m != nil {
		return m.Feerate
	}
	return 0
}

func (m *ParticipateResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *ParticipateResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type RedeemRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Hostport             string   `protobuf:"bytes,5,opt,name=hostport,proto3" json:"hostport,omitempty"`
	Rpcuser              string   `protobuf:"bytes,6,opt,name=rpcuser,proto3" json:"rpcuser,omitempty"`
	Rpcpass              string   `protobuf:"bytes,7,opt,name=rpcpass,proto3" json:"rpcpass,omitempty"`
	Secret               string   `protobuf:"bytes,8,opt,name=secret,proto3" json:"secret,omitempty"`
	Contract             string   `protobuf:"bytes,9,opt,name=contract,proto3" json:"contract,omitempty"`
	ContractTx           uint64   `protobuf:"varint,10,opt,name=contract_tx,json=contractTx,proto3" json:"contract_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedeemRequest) Reset()         { *m = RedeemRequest{} }
func (m *RedeemRequest) String() string { return proto.CompactTextString(m) }
func (*RedeemRequest) ProtoMessage()    {}
func (*RedeemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{8}
}

func (m *RedeemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemRequest.Unmarshal(m, b)
}
func (m *RedeemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemRequest.Marshal(b, m, deterministic)
}
func (m *RedeemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemRequest.Merge(m, src)
}
func (m *RedeemRequest) XXX_Size() int {
	return xxx_messageInfo_RedeemRequest.Size(m)
}
func (m *RedeemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemRequest proto.InternalMessageInfo

func (m *RedeemRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *RedeemRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *RedeemRequest) GetHostport() string {
	if m != nil {
		return m.Hostport
	}
	return ""
}

func (m *RedeemRequest) GetRpcuser() string {
	if m != nil {
		return m.Rpcuser
	}
	return ""
}

func (m *RedeemRequest) GetRpcpass() string {
	if m != nil {
		return m.Rpcpass
	}
	return ""
}

func (m *RedeemRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *RedeemRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *RedeemRequest) GetContractTx() uint64 {
	if m != nil {
		return m.ContractTx
	}
	return 0
}

type RedeemResponse struct {
	RedeemTx             string   `protobuf:"bytes,5,opt,name=redeem_tx,json=redeemTx,proto3" json:"redeem_tx,omitempty"`
	RedeemTxHash         string   `protobuf:"bytes,6,opt,name=redeem_tx_hash,json=redeemTxHash,proto3" json:"redeem_tx_hash,omitempty"`
	Fee                  int64    `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Feerate              float32  `protobuf:"fixed32,8,opt,name=feerate,proto3" json:"feerate,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedeemResponse) Reset()         { *m = RedeemResponse{} }
func (m *RedeemResponse) String() string { return proto.CompactTextString(m) }
func (*RedeemResponse) ProtoMessage()    {}
func (*RedeemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{9}
}

func (m *RedeemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemResponse.Unmarshal(m, b)
}
func (m *RedeemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemResponse.Marshal(b, m, deterministic)
}
func (m *RedeemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemResponse.Merge(m, src)
}
func (m *RedeemResponse) XXX_Size() int {
	return xxx_messageInfo_RedeemResponse.Size(m)
}
func (m *RedeemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemResponse proto.InternalMessageInfo

func (m *RedeemResponse) GetRedeemTx() string {
	if m != nil {
		return m.RedeemTx
	}
	return ""
}

func (m *RedeemResponse) GetRedeemTxHash() string {
	if m != nil {
		return m.RedeemTxHash
	}
	return ""
}

func (m *RedeemResponse) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RedeemResponse) GetFeerate() float32 {
	if m != nil {
		return m.Feerate
	}
	return 0
}

func (m *RedeemResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *RedeemResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type RefundRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Hostport             string   `protobuf:"bytes,5,opt,name=hostport,proto3" json:"hostport,omitempty"`
	Rpcuser              string   `protobuf:"bytes,6,opt,name=rpcuser,proto3" json:"rpcuser,omitempty"`
	Rpcpass              string   `protobuf:"bytes,7,opt,name=rpcpass,proto3" json:"rpcpass,omitempty"`
	Contract             string   `protobuf:"bytes,8,opt,name=contract,proto3" json:"contract,omitempty"`
	ContractTx           uint64   `protobuf:"varint,9,opt,name=contract_tx,json=contractTx,proto3" json:"contract_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundRequest) Reset()         { *m = RefundRequest{} }
func (m *RefundRequest) String() string { return proto.CompactTextString(m) }
func (*RefundRequest) ProtoMessage()    {}
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{10}
}

func (m *RefundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundRequest.Unmarshal(m, b)
}
func (m *RefundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundRequest.Marshal(b, m, deterministic)
}
func (m *RefundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundRequest.Merge(m, src)
}
func (m *RefundRequest) XXX_Size() int {
	return xxx_messageInfo_RefundRequest.Size(m)
}
func (m *RefundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefundRequest proto.InternalMessageInfo

func (m *RefundRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *RefundRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *RefundRequest) GetHostport() string {
	if m != nil {
		return m.Hostport
	}
	return ""
}

func (m *RefundRequest) GetRpcuser() string {
	if m != nil {
		return m.Rpcuser
	}
	return ""
}

func (m *RefundRequest) GetRpcpass() string {
	if m != nil {
		return m.Rpcpass
	}
	return ""
}

func (m *RefundRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *RefundRequest) GetContractTx() uint64 {
	if m != nil {
		return m.ContractTx
	}
	return 0
}

type RefundResponse struct {
	RefundTx             string   `protobuf:"bytes,5,opt,name=refund_tx,json=refundTx,proto3" json:"refund_tx,omitempty"`
	RefundTxHash         string   `protobuf:"bytes,6,opt,name=refund_tx_hash,json=refundTxHash,proto3" json:"refund_tx_hash,omitempty"`
	Fee                  int64    `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Feerate              float32  `protobuf:"fixed32,8,opt,name=feerate,proto3" json:"feerate,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundResponse) Reset()         { *m = RefundResponse{} }
func (m *RefundResponse) String() string { return proto.CompactTextString(m) }
func (*RefundResponse) ProtoMessage()    {}
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{11}
}

func (m *RefundResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundResponse.Unmarshal(m, b)
}
func (m *RefundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundResponse.Marshal(b, m, deterministic)
}
func (m *RefundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundResponse.Merge(m, src)
}
func (m *RefundResponse) XXX_Size() int {
	return xxx_messageInfo_RefundResponse.Size(m)
}
func (m *RefundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefundResponse proto.InternalMessageInfo

func (m *RefundResponse) GetRefundTx() string {
	if m != nil {
		return m.RefundTx
	}
	return ""
}

func (m *RefundResponse) GetRefundTxHash() string {
	if m != nil {
		return m.RefundTxHash
	}
	return ""
}

func (m *RefundResponse) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RefundResponse) GetFeerate() float32 {
	if m != nil {
		return m.Feerate
	}
	return 0
}

func (m *RefundResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *RefundResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type PublishRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Hostport             string   `protobuf:"bytes,5,opt,name=hostport,proto3" json:"hostport,omitempty"`
	Rpcuser              string   `protobuf:"bytes,6,opt,name=rpcuser,proto3" json:"rpcuser,omitempty"`
	Rpcpass              string   `protobuf:"bytes,7,opt,name=rpcpass,proto3" json:"rpcpass,omitempty"`
	Tx                   string   `protobuf:"bytes,8,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{12}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *PublishRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *PublishRequest) GetHostport() string {
	if m != nil {
		return m.Hostport
	}
	return ""
}

func (m *PublishRequest) GetRpcuser() string {
	if m != nil {
		return m.Rpcuser
	}
	return ""
}

func (m *PublishRequest) GetRpcpass() string {
	if m != nil {
		return m.Rpcpass
	}
	return ""
}

func (m *PublishRequest) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

type PublishResponse struct {
	TxHash               string   `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{13}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *PublishResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *PublishResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type ExtractSecretRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	CpRedemptionTx       string   `protobuf:"bytes,5,opt,name=cp_redemption_tx,json=cpRedemptionTx,proto3" json:"cp_redemption_tx,omitempty"`
	Secrethash           string   `protobuf:"bytes,6,opt,name=secrethash,proto3" json:"secrethash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractSecretRequest) Reset()         { *m = ExtractSecretRequest{} }
func (m *ExtractSecretRequest) String() string { return proto.CompactTextString(m) }
func (*ExtractSecretRequest) ProtoMessage()    {}
func (*ExtractSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{14}
}

func (m *ExtractSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractSecretRequest.Unmarshal(m, b)
}
func (m *ExtractSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractSecretRequest.Marshal(b, m, deterministic)
}
func (m *ExtractSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractSecretRequest.Merge(m, src)
}
func (m *ExtractSecretRequest) XXX_Size() int {
	return xxx_messageInfo_ExtractSecretRequest.Size(m)
}
func (m *ExtractSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractSecretRequest proto.InternalMessageInfo

func (m *ExtractSecretRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *ExtractSecretRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *ExtractSecretRequest) GetCpRedemptionTx() string {
	if m != nil {
		return m.CpRedemptionTx
	}
	return ""
}

func (m *ExtractSecretRequest) GetSecrethash() string {
	if m != nil {
		return m.Secrethash
	}
	return ""
}

type ExtractSecretResponse struct {
	Secret               string   `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractSecretResponse) Reset()         { *m = ExtractSecretResponse{} }
func (m *ExtractSecretResponse) String() string { return proto.CompactTextString(m) }
func (*ExtractSecretResponse) ProtoMessage()    {}
func (*ExtractSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{15}
}

func (m *ExtractSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractSecretResponse.Unmarshal(m, b)
}
func (m *ExtractSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractSecretResponse.Marshal(b, m, deterministic)
}
func (m *ExtractSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractSecretResponse.Merge(m, src)
}
func (m *ExtractSecretResponse) XXX_Size() int {
	return xxx_messageInfo_ExtractSecretResponse.Size(m)
}
func (m *ExtractSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractSecretResponse proto.InternalMessageInfo

func (m *ExtractSecretResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *ExtractSecretResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *ExtractSecretResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

type AuditRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Testnet              bool     `protobuf:"varint,2,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Contract             string   `protobuf:"bytes,5,opt,name=contract,proto3" json:"contract,omitempty"`
	ContractTx           uint64   `protobuf:"varint,6,opt,name=contract_tx,json=contractTx,proto3" json:"contract_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditRequest) Reset()         { *m = AuditRequest{} }
func (m *AuditRequest) String() string { return proto.CompactTextString(m) }
func (*AuditRequest) ProtoMessage()    {}
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{16}
}

func (m *AuditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditRequest.Unmarshal(m, b)
}
func (m *AuditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditRequest.Marshal(b, m, deterministic)
}
func (m *AuditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditRequest.Merge(m, src)
}
func (m *AuditRequest) XXX_Size() int {
	return xxx_messageInfo_AuditRequest.Size(m)
}
func (m *AuditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuditRequest proto.InternalMessageInfo

func (m *AuditRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *AuditRequest) GetTestnet() bool {
	if m != nil {
		return m.Testnet
	}
	return false
}

func (m *AuditRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *AuditRequest) GetContractTx() uint64 {
	if m != nil {
		return m.ContractTx
	}
	return 0
}

type AuditResponse struct {
	ContractAmount       int64    `protobuf:"varint,5,opt,name=contract_amount,json=contractAmount,proto3" json:"contract_amount,omitempty"`
	ContractAddress      string   `protobuf:"bytes,6,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ContractSecrethash   string   `protobuf:"bytes,7,opt,name=contract_secrethash,json=contractSecrethash,proto3" json:"contract_secrethash,omitempty"`
	RecipientAddress     string   `protobuf:"bytes,8,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	RefundAddress        string   `protobuf:"bytes,9,opt,name=refund_address,json=refundAddress,proto3" json:"refund_address,omitempty"`
	RefundLocktime       uint64   `protobuf:"varint,10,opt,name=refund_locktime,json=refundLocktime,proto3" json:"refund_locktime,omitempty"`
	Errorno              int32    `protobuf:"varint,14,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errstr               string   `protobuf:"bytes,15,opt,name=errstr,proto3" json:"errstr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditResponse) Reset()         { *m = AuditResponse{} }
func (m *AuditResponse) String() string { return proto.CompactTextString(m) }
func (*AuditResponse) ProtoMessage()    {}
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9afe1911bb3b5204, []int{17}
}

func (m *AuditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditResponse.Unmarshal(m, b)
}
func (m *AuditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditResponse.Marshal(b, m, deterministic)
}
func (m *AuditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditResponse.Merge(m, src)
}
func (m *AuditResponse) XXX_Size() int {
	return xxx_messageInfo_AuditResponse.Size(m)
}
func (m *AuditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuditResponse proto.InternalMessageInfo

func (m *AuditResponse) GetContractAmount() int64 {
	if m != nil {
		return m.ContractAmount
	}
	return 0
}

func (m *AuditResponse) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *AuditResponse) GetContractSecrethash() string {
	if m != nil {
		return m.ContractSecrethash
	}
	return ""
}

func (m *AuditResponse) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *AuditResponse) GetRefundAddress() string {
	if m != nil {
		return m.RefundAddress
	}
	return ""
}

func (m *AuditResponse) GetRefundLocktime() uint64 {
	if m != nil {
		return m.RefundLocktime
	}
	return 0
}

func (m *AuditResponse) GetErrorno() int32 {
	if m != nil {
		return m.Errorno
	}
	return 0
}

func (m *AuditResponse) GetErrstr() string {
	if m != nil {
		return m.Errstr
	}
	return ""
}

func init() {
	proto.RegisterType((*PingWalletRpcRequest)(nil), "protobind.PingWalletRpcRequest")
	proto.RegisterType((*PingWalletRpcResponse)(nil), "protobind.PingWalletRpcResponse")
	proto.RegisterType((*NewAddressRequest)(nil), "protobind.NewAddressRequest")
	proto.RegisterType((*NewAddressResponse)(nil), "protobind.NewAddressResponse")
	proto.RegisterType((*InitiateRequest)(nil), "protobind.InitiateRequest")
	proto.RegisterType((*InitiateResponse)(nil), "protobind.InitiateResponse")
	proto.RegisterType((*ParticipateRequest)(nil), "protobind.ParticipateRequest")
	proto.RegisterType((*ParticipateResponse)(nil), "protobind.ParticipateResponse")
	proto.RegisterType((*RedeemRequest)(nil), "protobind.RedeemRequest")
	proto.RegisterType((*RedeemResponse)(nil), "protobind.RedeemResponse")
	proto.RegisterType((*RefundRequest)(nil), "protobind.RefundRequest")
	proto.RegisterType((*RefundResponse)(nil), "protobind.RefundResponse")
	proto.RegisterType((*PublishRequest)(nil), "protobind.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "protobind.PublishResponse")
	proto.RegisterType((*ExtractSecretRequest)(nil), "protobind.ExtractSecretRequest")
	proto.RegisterType((*ExtractSecretResponse)(nil), "protobind.ExtractSecretResponse")
	proto.RegisterType((*AuditRequest)(nil), "protobind.AuditRequest")
	proto.RegisterType((*AuditResponse)(nil), "protobind.AuditResponse")
}

func init() { proto.RegisterFile("atomicswap.proto", fileDescriptor_9afe1911bb3b5204) }

var fileDescriptor_9afe1911bb3b5204 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x97, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0xc7, 0xb5, 0x69, 0x93, 0xd8, 0xd3, 0x7c, 0x75, 0xfb, 0x71, 0xac, 0x73, 0xa4, 0x43, 0x30,
	0xa0, 0x06, 0x21, 0x81, 0x54, 0x9e, 0xa0, 0x17, 0x48, 0x54, 0x42, 0x28, 0x72, 0x2b, 0x71, 0x83,
	0x14, 0x5c, 0x67, 0x4b, 0x56, 0x24, 0xf6, 0xb2, 0xbb, 0x51, 0xcd, 0x4b, 0x20, 0x21, 0x71, 0xcd,
	0x3b, 0x20, 0xf1, 0x06, 0xdc, 0xf5, 0x31, 0xb8, 0xe7, 0x19, 0x40, 0xbb, 0xde, 0x75, 0x1c, 0xf7,
	0x23, 0x34, 0x95, 0x50, 0xae, 0xba, 0x33, 0x3b, 0x6b, 0xcf, 0x7f, 0x7e, 0xb3, 0x9e, 0x06, 0x3a,
	0xa1, 0x4c, 0x26, 0x34, 0x12, 0x67, 0x21, 0x7b, 0xcc, 0x78, 0x22, 0x13, 0xec, 0xea, 0x3f, 0x27,
	0x34, 0x1e, 0xfa, 0x9f, 0x11, 0x6c, 0xf7, 0x69, 0xfc, 0xf6, 0x55, 0x38, 0x1e, 0x13, 0x19, 0xb0,
	0x28, 0x20, 0xef, 0xa7, 0x44, 0x48, 0x8c, 0x61, 0x3d, 0x4a, 0x68, 0xec, 0xa1, 0x2e, 0xea, 0xb9,
	0x81, 0x5e, 0x63, 0x0f, 0xea, 0x92, 0x08, 0x19, 0x13, 0xe9, 0x55, 0xba, 0xa8, 0xe7, 0x04, 0xd6,
	0xc4, 0xff, 0x82, 0x33, 0x4a, 0x84, 0x64, 0x09, 0x97, 0x5e, 0x55, 0x9f, 0xc8, 0x6d, 0x75, 0x8a,
	0xb3, 0x68, 0x2a, 0x08, 0xf7, 0x6a, 0x7a, 0xcb, 0x9a, 0x66, 0x87, 0x85, 0x42, 0x78, 0xf5, 0x7c,
	0x47, 0x99, 0xfe, 0x21, 0xec, 0x94, 0xb2, 0x12, 0x2c, 0x89, 0x05, 0x51, 0x47, 0x08, 0xe7, 0x09,
	0x8f, 0x13, 0xaf, 0xd5, 0x45, 0xbd, 0x6a, 0x60, 0x4d, 0xbc, 0x0b, 0x35, 0xc2, 0xb9, 0x90, 0xdc,
	0x6b, 0xeb, 0x67, 0x19, 0xcb, 0xff, 0x84, 0x60, 0xf3, 0x25, 0x39, 0x3b, 0x18, 0x0e, 0x39, 0x11,
	0x62, 0x35, 0xe4, 0xbd, 0x01, 0x5c, 0x4c, 0x69, 0xa6, 0x2d, 0xcc, 0x5c, 0xe6, 0x25, 0xd6, 0x5c,
	0x42, 0xf5, 0x39, 0x82, 0xf6, 0x61, 0x4c, 0x25, 0x0d, 0x25, 0x59, 0x09, 0xcd, 0xf8, 0x2e, 0x34,
	0x58, 0xc8, 0xe5, 0xc0, 0x4a, 0x74, 0xf4, 0xf6, 0x86, 0xf2, 0x99, 0x42, 0x28, 0x31, 0xe1, 0x24,
	0x99, 0xc6, 0xd2, 0x73, 0xbb, 0xa8, 0xb7, 0x16, 0x18, 0xcb, 0xff, 0x56, 0x81, 0xce, 0x4c, 0x8c,
	0xa9, 0xd6, 0x2e, 0xd4, 0x04, 0x89, 0x38, 0xb1, 0xd9, 0x19, 0x0b, 0xff, 0x0f, 0x90, 0xad, 0x46,
	0xa1, 0x18, 0x99, 0xf4, 0x0a, 0x1e, 0xa5, 0x2b, 0x4a, 0x62, 0xc9, 0xc3, 0x48, 0x9a, 0x14, 0x73,
	0x1b, 0xdf, 0x83, 0xa6, 0x5d, 0x0f, 0xd8, 0xbe, 0x18, 0x99, 0x24, 0x1b, 0xd6, 0xd9, 0xdf, 0x17,
	0x23, 0x7c, 0x07, 0x36, 0xf2, 0x20, 0x99, 0xea, 0x54, 0xdd, 0x00, 0xac, 0xeb, 0x38, 0xc5, 0x3d,
	0xe8, 0x14, 0x02, 0x06, 0x3a, 0x0f, 0xd0, 0x51, 0xad, 0x59, 0xd4, 0x73, 0x95, 0x4b, 0x07, 0xd6,
	0x4e, 0x09, 0xf1, 0x36, 0xb4, 0x5a, 0xb5, 0x54, 0xf5, 0x3b, 0x25, 0x84, 0x87, 0x92, 0x78, 0x8d,
	0x2e, 0xea, 0x55, 0x02, 0x6b, 0x2e, 0xd1, 0x03, 0x3f, 0x11, 0xe0, 0x7e, 0xc8, 0x25, 0x8d, 0x28,
	0x5b, 0x99, 0x36, 0x98, 0xc7, 0xe3, 0x5c, 0xc0, 0x53, 0x6e, 0x13, 0xf7, 0xba, 0x36, 0x81, 0xb9,
	0x36, 0xf9, 0x85, 0x60, 0x6b, 0x4e, 0xaf, 0xe9, 0x94, 0x22, 0xf1, 0xea, 0x22, 0xe2, 0xb5, 0xc5,
	0xc4, 0xeb, 0x7f, 0x44, 0xdc, 0xb9, 0x8e, 0xb8, 0x7b, 0x29, 0x71, 0xb8, 0x2d, 0xf1, 0x1f, 0x08,
	0x9a, 0x01, 0x19, 0x12, 0x32, 0x59, 0x0d, 0xd8, 0xb3, 0x3b, 0xea, 0xcc, 0xdd, 0xd1, 0x22, 0x11,
	0xb7, 0x44, 0xa4, 0x54, 0x6c, 0x55, 0x93, 0xf5, 0x62, 0xb1, 0xfd, 0xaf, 0x08, 0x5a, 0x56, 0xa4,
	0x21, 0xfc, 0x1f, 0xb8, 0x5c, 0x7b, 0xd4, 0x09, 0x93, 0x78, 0xe6, 0x38, 0x4e, 0xf1, 0x7d, 0x68,
	0xe5, 0x9b, 0x83, 0xc2, 0x47, 0xa1, 0x61, 0x23, 0x8a, 0x60, 0xea, 0x97, 0x82, 0x71, 0x6e, 0x0b,
	0xe6, 0x5c, 0x83, 0x39, 0x9d, 0xc6, 0xc3, 0xd5, 0x00, 0x53, 0x04, 0xe0, 0x5c, 0x0f, 0xc0, 0xbd,
	0x02, 0x40, 0x26, 0xa6, 0x08, 0x40, 0x79, 0xe6, 0x00, 0x28, 0x87, 0x05, 0x60, 0x36, 0x4b, 0x00,
	0xb2, 0x88, 0xbf, 0x00, 0xe0, 0x0b, 0x82, 0x56, 0x7f, 0x7a, 0x32, 0xa6, 0x62, 0xb4, 0x1a, 0x04,
	0x5a, 0x50, 0x91, 0xa9, 0xa9, 0x7d, 0x45, 0xa6, 0xfe, 0x6b, 0x68, 0xe7, 0xf9, 0x99, 0xa2, 0xfe,
	0x03, 0x75, 0x5b, 0x30, 0x33, 0xe2, 0x64, 0x56, 0xaa, 0x9b, 0xcb, 0xff, 0x88, 0x60, 0xfb, 0x59,
	0xaa, 0x01, 0x1e, 0xe9, 0x2b, 0xb8, 0x5c, 0x11, 0xd4, 0x77, 0x8e, 0x0d, 0xd4, 0xbd, 0x99, 0x30,
	0x49, 0x93, 0x78, 0x46, 0xbb, 0x15, 0xb1, 0x20, 0x77, 0x1f, 0xa7, 0x8b, 0xa6, 0xb0, 0x1f, 0xc2,
	0x4e, 0x29, 0x9f, 0x05, 0x63, 0xfd, 0xe6, 0x9a, 0x3f, 0x40, 0xe3, 0x60, 0x3a, 0xa4, 0x72, 0x69,
	0xde, 0x57, 0x0e, 0x8d, 0xd2, 0x0d, 0xa9, 0x5d, 0xb8, 0x21, 0xdf, 0x2b, 0xd0, 0x34, 0xef, 0x36,
	0xb2, 0xf6, 0xa0, 0x9d, 0x1f, 0x31, 0xc3, 0xab, 0xaa, 0x3b, 0x3d, 0x1f, 0x10, 0x07, 0xda, 0x8b,
	0x1f, 0x16, 0x46, 0x89, 0x9d, 0x81, 0x59, 0xf9, 0xf2, 0x07, 0xd8, 0x39, 0xf8, 0x04, 0xb6, 0xf2,
	0xd0, 0x42, 0xb1, 0xb3, 0x46, 0xc3, 0x76, 0xeb, 0x68, 0x36, 0x5b, 0x1f, 0xc1, 0x26, 0x27, 0x11,
	0x65, 0x94, 0xc4, 0xe5, 0xff, 0xc3, 0x3a, 0xf9, 0x86, 0x7d, 0xfa, 0x83, 0xfc, 0xd6, 0xce, 0x8f,
	0xe2, 0x66, 0xe6, 0xb5, 0x61, 0x7b, 0xd0, 0x36, 0x61, 0xe3, 0x24, 0x7a, 0x27, 0xe9, 0x84, 0x98,
	0x4f, 0xb6, 0x39, 0xfd, 0xc2, 0x78, 0x6f, 0x0e, 0xf0, 0xa4, 0xa6, 0x7f, 0xa6, 0x3c, 0xfd, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0x36, 0xb7, 0xef, 0xc1, 0x0c, 0x00, 0x00,
}
